# Site settings
title: Tumbling Owl
email: cdr255@gmail.com
description: "The personal web log of Christopher Rodriguez."
baseurl: ""
url: "http://www.tumblingowl.com"


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
